// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.6.1
// source: proto/ratio.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetRatiosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRatiosRequest) Reset() {
	*x = GetRatiosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ratio_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRatiosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatiosRequest) ProtoMessage() {}

func (x *GetRatiosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratio_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatiosRequest.ProtoReflect.Descriptor instead.
func (*GetRatiosRequest) Descriptor() ([]byte, []int) {
	return file_proto_ratio_proto_rawDescGZIP(), []int{0}
}

type GetRatiosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ratios []*GetRatiosResponse_Ratio `protobuf:"bytes,1,rep,name=ratios,proto3" json:"ratios,omitempty"`
}

func (x *GetRatiosResponse) Reset() {
	*x = GetRatiosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ratio_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRatiosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatiosResponse) ProtoMessage() {}

func (x *GetRatiosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratio_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatiosResponse.ProtoReflect.Descriptor instead.
func (*GetRatiosResponse) Descriptor() ([]byte, []int) {
	return file_proto_ratio_proto_rawDescGZIP(), []int{1}
}

func (x *GetRatiosResponse) GetRatios() []*GetRatiosResponse_Ratio {
	if x != nil {
		return x.Ratios
	}
	return nil
}

type GetRatiosResponse_Ratio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Currency string  `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Ratio    float32 `protobuf:"fixed32,2,opt,name=ratio,proto3" json:"ratio,omitempty"`
}

func (x *GetRatiosResponse_Ratio) Reset() {
	*x = GetRatiosResponse_Ratio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ratio_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRatiosResponse_Ratio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatiosResponse_Ratio) ProtoMessage() {}

func (x *GetRatiosResponse_Ratio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratio_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatiosResponse_Ratio.ProtoReflect.Descriptor instead.
func (*GetRatiosResponse_Ratio) Descriptor() ([]byte, []int) {
	return file_proto_ratio_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetRatiosResponse_Ratio) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetRatiosResponse_Ratio) GetRatio() float32 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

var File_proto_ratio_proto protoreflect.FileDescriptor

var file_proto_ratio_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x80, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x52,
	0x61, 0x74, 0x69, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a,
	0x06, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x73, 0x1a,
	0x39, 0x0a, 0x05, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x05, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x32, 0x47, 0x0a, 0x0f, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x46, 0x65, 0x74, 0x63, 0x68, 0x65, 0x72, 0x12, 0x34, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x73, 0x12, 0x11, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x61, 0x74, 0x69, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x4e, 0x6f, 0x74, 0x53, 0x6f, 0x46, 0x61, 0x6e, 0x63, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x2f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_ratio_proto_rawDescOnce sync.Once
	file_proto_ratio_proto_rawDescData = file_proto_ratio_proto_rawDesc
)

func file_proto_ratio_proto_rawDescGZIP() []byte {
	file_proto_ratio_proto_rawDescOnce.Do(func() {
		file_proto_ratio_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ratio_proto_rawDescData)
	})
	return file_proto_ratio_proto_rawDescData
}

var file_proto_ratio_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_ratio_proto_goTypes = []interface{}{
	(*GetRatiosRequest)(nil),        // 0: GetRatiosRequest
	(*GetRatiosResponse)(nil),       // 1: GetRatiosResponse
	(*GetRatiosResponse_Ratio)(nil), // 2: GetRatiosResponse.Ratio
}
var file_proto_ratio_proto_depIdxs = []int32{
	2, // 0: GetRatiosResponse.ratios:type_name -> GetRatiosResponse.Ratio
	0, // 1: CurrencyFetcher.GetRatios:input_type -> GetRatiosRequest
	1, // 2: CurrencyFetcher.GetRatios:output_type -> GetRatiosResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_ratio_proto_init() }
func file_proto_ratio_proto_init() {
	if File_proto_ratio_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ratio_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRatiosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ratio_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRatiosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ratio_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRatiosResponse_Ratio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ratio_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ratio_proto_goTypes,
		DependencyIndexes: file_proto_ratio_proto_depIdxs,
		MessageInfos:      file_proto_ratio_proto_msgTypes,
	}.Build()
	File_proto_ratio_proto = out.File
	file_proto_ratio_proto_rawDesc = nil
	file_proto_ratio_proto_goTypes = nil
	file_proto_ratio_proto_depIdxs = nil
}
